# Generated by Django 5.0.4 on 2024-04-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MPesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_request_id', models.CharField(max_length=100, unique=True, verbose_name='Merchant Request ID')),
                ('checkout_request_id', models.CharField(max_length=100, unique=True, verbose_name='Checkout Request ID')),
                ('response_code', models.CharField(db_index=True, max_length=10, verbose_name='Response Code')),
                ('response_description', models.CharField(max_length=255, verbose_name='Response Description')),
                ('customer_message', models.CharField(max_length=255, verbose_name='Customer Message')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('amount', models.IntegerField(default=0, verbose_name='Amount')),
                ('account_reference', models.CharField(max_length=50, verbose_name='Account Reference')),
                ('transaction_desc', models.CharField(max_length=255, verbose_name='Transaction Description')),
            ],
            options={
                'verbose_name': 'M-Pesa Transaction',
                'verbose_name_plural': 'M-Pesa Transactions',
                'indexes': [models.Index(fields=['response_code'], name='mpesa_trans_respons_187401_idx')],
            },
        ),
    ]
