# Generated by Django 5.0.4 on 2024-04-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mpesatransaction',
            name='mpesa_trans_respons_187401_idx',
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='amount',
            field=models.IntegerField(verbose_name='Amount'),
        ),
    ]
