# Generated by Django 5.0.4 on 2024-04-23 16:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_transactions', '0002_remove_mpesatransaction_mpesa_trans_respons_187401_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesatransaction',
            name='checkout_request_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Checkout Request ID'),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='merchant_request_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Merchant Request ID'),
        ),
    ]
